### ISSUE TITLE
MIT License

### ISSUE THREAD

**Issue by nikolazius** [radko93/RANSAC#1]
Would you mind releasing under MIT license?
Thank you in advance!

**Comment by radko93** [comment]
Hey, why do you need it?

**Comment by nikolazius** [comment]
Hi, thank you for the reply! Community will definitely benefit.

To be honest, there is no specific use at the moment. I've seen some quality code and wanted to show to few guys, but if the license is not permitting, I don't want them even to have a peek at it. 

Otherwise it won't be fair in regards to you an your work, even if hosted on GitHub.

**Comment by radko93** [comment]
OK it's MIT now.
